### PR TITLE
WIP:  Indicating whether the query still runs after changes in the DB

### PR DESCRIPTION
**Pull request by eeriksp**
Solves #542

### CODE REVIEW

**Comment by eeriksp** [comment]
Here is a screenshot of the list view (notice the "Ran Successfully" column):
image

**Comment by marksweb** [comment]
I'll have a look over this, but there's some test failures & linting issues that look like a good place to start on more changes.

**Comment by chrisclark** [comment]
Heyo! I'm jumping back into some dev here -- I think this is a totally cool idea. I wonder if it is possible to source it from the querylog however, rather than creating a new field and having to manage the state of it. I'll make a stab at it and tell me what you think.

**Comment by chrisclark** [comment]
Here it is, but doesn't require adding any statefulness -- just expanding what's captured in the query logs. I like this event-sourced pattern of tracking the run history of Queries.

https://github.com/chrisclark/django-sql-explorer/pull/562

**Comment by chrisclark** [comment]
Addressed in https://github.com/chrisclark/django-sql-explorer/pull/562

**Comment by chrisclark** [comment]
Happy to accept a separate PR for the script part that re-runs all queries and checks whether they will execute.

**Pull request closed without merging**
